// 创建文件en.js
const en = {
    button: {

    },
    login: {
        注册: 'Regist',
        请输入用户名: 'Enter user name',
        请输入密码: 'Enter password',
        请输入手机号: 'Enter phone number',
        请填写正确的手机号: 'Please fill correct number',
        注册成功: 'Successful Registration',
        '注册失败，手机号重复': 'Registration failure,Duplicate phone number!',
        请稍后重试: 'Please try again later',
        发送成功: 'Send successfully',
        发送失败: 'Send failure',
        验证码登录: 'Verification code login',
        '登陆中...': 'Login...',
        手机号或密码错误: 'Mobile phone or password error',
        登陆成功: 'Login success',
        密码登录: 'password login',
        请输入验证码: 'Enter verification code',
        获取验证码: 'Send Code',
        请填写正确的验证码: 'Please fill correct code',
    },
    my: {
        登录: 'Login',
        编辑资料: 'Edit Data',
        头条: 'Articles',
        关注: 'Follows',
        粉丝: 'Fans',
        获赞: 'Likes',
        收藏: 'Collect',
        历史: 'History',
        消息通知: 'Message',
        语言: 'Language',
        退出登陆: 'Log Out',
        是否退出登陆: 'Whether to log out?',
        加载失败: 'Load Failure',
        请输入搜索关键词: 'Enter search terms',
        搜索历史: 'Search History',
        全部删除: 'Delete All  ',
        完成: 'Compelete',
        没有更多了: 'No more',
        '获取推荐列表失败，请稍后重试': 'Get list failure,Please try again later',
        首页: 'Home',
        我的: 'my',
        未登录: 'Login',
        搜索: 'Search',
        '请求失败，点击重新加载': 'Request error,click to refresh',
        我的频道: 'My Channels',
        编辑: 'edit',
        频道列表: 'Channels',
        获取文章列表失败: 'Get article list failure',
        保存失败: 'Save failure',
        删除失败: 'Delete failure',
        新闻头条: 'HeadLines',
        加载中: 'Loading',
        '该资源不存在或已删除！': 'Resource Not Found',
        '内容加载失败！': 'Content Loading Failure',
        点击重试: 'click to refresh',
        获取新闻内容失败: 'Get article content failure',
        回复: 'reply',
        '获取文章评论失败，请稍后重试': 'Get comments Failure,Please try again later',
        请输入留言: 'Enter comments',
        评论成功: 'Review Success',
        评论失败: 'Review Failure',
        全部回复: 'All reply',
        写评论: 'Write Comments',
        正文结束: 'End Of Text',
        评论: 'Comment',
        选择生日: 'Select Birthday',
        修改成功: 'Modified Successfully',
        修改生日失败: 'Modified Failure',
        修改性别: 'Modify Gender',
        男: 'male',
        女: 'demale',
        修改性别失败: 'Modified Failure',
        设置昵称: 'Set Nickname',
        请输入新昵称: 'Enter new nickname',
        昵称不能为空: 'Nickname cannot be empty',
        修改昵称失败: 'Modified Failure',
        取消: 'Cancel',
        个人信息: 'Personal Information',
        头像: 'Pic',
        昵称: 'Nickname',
        性别: 'Gender',
        生日: 'Birthday',
        获取用户个人信息失败: 'Get information failure',
        取消收藏: 'Uncollect',
        收藏成功: 'Collect',
        收藏失败: 'Collect Failure',
        已关注: 'Followed',
        关注: '关注',
        关注: 'Follow',
        不能关注自己哦: 'Cannot follow yourself',
        关注失败: 'Followed Failure',
        取消点赞: 'Unlike Success',
        点赞成功: 'Like Success',
        点赞或取消点赞失败: 'Operation Failure',
        收藏: 'Collected Articles',
        历史: 'History',
        关注: 'Followed',
        我的文章: 'My Articles',
        发布文章: 'Release News',
        返回: 'Back',
        标题: 'Title',
        分区: 'Channel',
        内容: 'Content',
        请输入内容: 'Enter content',
        发布: 'Public',
        上传成功: 'Public successfully',
        上传失败: 'Public failure',
        审核文章: 'Audit'
    }
}
export default en;